// art/manifest.js — GENERATED by tools/gen-art.mjs. Do not edit by hand.
//
// Declared on the page EMPTY and failing loudly before a single render exists, because on
// project 5 this file was generated but never added to index.html and js/art.js read
// `RF.artManifest || {}` — so the page silently drew placeholder art for 59 paid renders and
// said nothing (CARD-GAME-LESSONS-5.md §5.3). js/art.js throws if this object is absent.
(function (NS) {
  'use strict';
  NS.artManifest = {};
  NS.artMeta = { generated: null, count: 0, style: null };
}(window.OP = window.OP || {}));
