// audio/manifest.js — GENERATED by tools/gen-sfx.mjs. Do not edit by hand.
//
// One-shots generated for this project from a text description, layered over the synthesised
// floor in js/audio.js. A tag with no entry here keeps its synthesised voice, which is why the
// kit may be partial and why nothing breaks if this file is empty.
//
// Declared on the page even while empty; js/audio.js THROWS if it is absent (hard rule 11).
(function (NS) {
  'use strict';
  NS.sfxManifest = {
    "battle.blocked": "audio/sfx/battle_blocked.mp3",
    "battle.declared": "audio/sfx/battle_declared.mp3",
    "card.played": "audio/sfx/card_played.mp3",
    "char.ko": "audio/sfx/char_ko.mp3",
    "counter.played": "audio/sfx/counter_played.mp3",
    "don.given": "audio/sfx/don_given.mp3",
    "event.played": "audio/sfx/event_played.mp3",
    "life.critical": "audio/sfx/life_critical.mp3",
    "life.taken": "audio/sfx/life_taken.mp3",
    "lose": "audio/sfx/lose.mp3",
    "stage.played": "audio/sfx/stage_played.mp3",
    "trigger.used": "audio/sfx/trigger_used.mp3",
    "win": "audio/sfx/win.mp3"
  };
}(window.OP = window.OP || {}));
