#!/usr/bin/env node
// tools/build-decks.mjs — generate data/decks.js, the deck registry.
//
// The registry decides the pool: a card that is not in a registered deck is not in the game.
// Every slot records where it came from, because the two sources are not equally strong:
//
//   measured  — onepiece.gg's "Most played cards" table for that archetype, with its own copy
//               count and inclusion rate (scratch/decks/onepiece-gg-meta-2026-09-26.json).
//   inferred  — chosen here to complete a legal 50. onepiece.gg's free tier publishes only the
//               twelve most-played cards, which is about 43 of 50 slots.
//
// Nothing is invented silently; the deck screen shows the split. PLAN.md D5.
//
// Every card in a registered deck must COMPILE (CLAUDE.md hard rule 8). A card whose printed
// text the grammar cannot express is skipped and the skip is reported, so a deck never contains
// a card that would not do what it says.
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const load = async (rel) => {
  const src = await readFile(join(ROOT, rel), 'utf8');
  const w = {};
  new Function('window', src)(w);
  return w.OP;
};
const P = await load('data/printed.js');
const A = (await load('data/abilities.js')).abilities;
const META = JSON.parse(await readFile(join(ROOT, 'scratch/decks/onepiece-gg-meta-2026-09-26.json'), 'utf8'));

const BY_ID = new Map(P.printed.map((c) => [c.id, c]));
const compiles = (id) => A[id] && !A[id].unimplemented;
const setRank = (id) => {                      // newest printing first, for name resolution
  const m = id.match(/^([A-Z]+)(\d+)-/);
  if (!m) return 0;
  const base = { OP: 300, EB: 250, PRB: 240, ST: 200 }[m[1]] || 100;
  return base + Number(m[2]);
};

function legalWith(leaderId, c) {
  const L = BY_ID.get(leaderId);
  if (c.category === 'LEADER') return false;
  return c.color.some((col) => L.color.includes(col));
}

// ---------------------------------------------------------------------------------------
// Starter decks. Bandai publishes the 17 cards of an ST product and its rarity split
// (1 Leader, 2 SR, 14 Common) but NOT the per-card quantities — checked on the official
// product page on 2026-09-26, see docs/rights.md. The counts below are therefore generated by
// a stated rule rather than asserted as printed:
//
//   2 copies of each SR, then the remaining slots spread as evenly as possible across the
//   Commons at no more than 4 each (CR 5-1-2-3), lowest card number first on ties.
//
// That gives a legal 50 from the real 16 cards. `countsInferred` marks it on the deck.
// ---------------------------------------------------------------------------------------
function starterDeck(prefix) {
  const cards = P.printed.filter((c) => c.id.startsWith(prefix + '-')).sort((a, b) => a.id.localeCompare(b.id));
  const leader = cards.find((c) => c.category === 'LEADER');
  const pool = cards.filter((c) => c.category !== 'LEADER' && compiles(c.id));
  const skipped = cards.filter((c) => c.category !== 'LEADER' && !compiles(c.id)).map((c) => c.id);

  const list = [];
  const srs = pool.filter((c) => c.rarity === 'SR');
  const commons = pool.filter((c) => c.rarity !== 'SR');
  srs.forEach((c) => { list.push([c.id, 2, 'inferred']); });
  let left = 50 - srs.length * 2;
  const per = Math.floor(left / commons.length);
  let extra = left - per * commons.length;
  commons.forEach((c) => {
    let n = Math.min(4, per + (extra > 0 ? 1 : 0));
    if (extra > 0) extra--;
    list.push([c.id, n, 'inferred']);
    left -= n;
  });
  // Top up or trim to land exactly on 50 without breaking the 4-of limit.
  let total = list.reduce((a, x) => a + x[1], 0);
  for (let i = 0; total < 50 && i < list.length * 4; i++) {
    const e = list[i % list.length];
    if (e[1] < 4) { e[1]++; total++; }
  }
  for (let i = list.length - 1; total > 50 && i >= 0; i--) {
    while (list[i][1] > 1 && total > 50) { list[i][1]--; total--; }
  }
  return { leader: leader.id, list, skipped };
}

// ---------------------------------------------------------------------------------------
// Meta decks.
// ---------------------------------------------------------------------------------------
function resolveName(leaderId, name) {
  const cands = P.printed.filter((c) => c.name === name && legalWith(leaderId, c) && compiles(c.id));
  if (!cands.length) return null;
  cands.sort((a, b) => setRank(b.id) - setRank(a.id) || a.id.localeCompare(b.id));
  return { id: cands[0].id, ambiguous: cands.length > 1, among: cands.length };
}

function metaDeck(arch) {
  const leaderId = arch.leader;
  const list = [];
  const notes = [];
  let total = 0;

  // Two measured rows can name the same character (onepiece.gg counts a parallel art as its own
  // row, and an archetype may run two different printings of one name). Both then resolve to the
  // same card number here, so copies are accumulated per NUMBER and capped at 4 (CR 5-1-2-3).
  const byNumber = new Map();
  for (const [name, copies, rate] of arch.mostPlayed) {
    if (name === BY_ID.get(leaderId).name && copies === 1) continue;   // the Leader's own row
    const r = resolveName(leaderId, name);
    if (!r) { notes.push(`"${name}" ${copies}x — no colour-legal printing this engine can play`); continue; }
    if (total >= 50) break;
    const already = byNumber.get(r.id) || 0;
    const n = Math.min(4 - already, copies, 50 - total);
    if (n <= 0) { if (already) notes.push(`"${name}" ${copies}x — folds into ${r.id}, already at 4 copies`); continue; }
    byNumber.set(r.id, already + n);
    const prev = list.find((x) => x[0] === r.id);
    if (prev) prev[1] += n; else list.push([r.id, n, 'measured', rate, r.ambiguous ? r.among : 0]);
    total += n;
  }

  // Fill the rest from the archetype's own colour pool: prefer cards sharing a type with what
  // is already in the deck, then a low cost with a Counter value, so the curve stays playable.
  const have = new Set(list.map((x) => x[0]));
  const types = new Set();
  list.forEach(([id]) => BY_ID.get(id).types.forEach((t) => types.add(t)));
  const fill = P.printed
    .filter((c) => legalWith(leaderId, c) && compiles(c.id) && !have.has(c.id))
    .map((c) => ({
      c,
      score: (c.types.some((t) => types.has(t)) ? 100 : 0) +
             (c.counter ? 20 : 0) +
             (c.category === 'CHARACTER' ? 10 : 0) +
             Math.max(0, 8 - (c.cost || 0)) * 3 +
             setRank(c.id) / 100
    }))
    .sort((a, b) => b.score - a.score);

  for (const f of fill) {
    if (total >= 50) break;
    const n = Math.min(4, 50 - total);
    list.push([f.c.id, n, 'inferred', null, 0]);
    total += n;
  }
  return { leader: leaderId, list, notes, measured: list.filter((x) => x[2] === 'measured').reduce((a, x) => a + x[1], 0) };
}

// ---------------------------------------------------------------------------------------
const decks = [];

for (const [prefix, key, name, blurb] of [
  ['ST01', 'st01', 'Straw Hat Crew', 'Bandai starter deck ST-01. Red, aggressive, built on [Rush] and DON!! attachment.'],
  ['ST02', 'st02', 'Worst Generation', 'Bandai starter deck ST-02. Green, built on resting and re-activating.']
]) {
  const d = starterDeck(prefix);
  decks.push({ key, name, kind: 'starter', leader: d.leader,
    blurb, source: 'Bandai starter product ' + prefix.replace(/(\D+)(\d+)/, '$1-$2'),
    countsInferred: true, list: d.list.map(([id, n]) => [id, n, 'inferred', null, 0]),
    skipped: d.skipped, notes: [] });
}

for (const arch of META.archetypes) {
  const d = metaDeck(arch);
  decks.push({
    key: arch.leader.toLowerCase(), name: arch.name, kind: 'meta',
    leader: d.leader, tier: arch.tier, rank: arch.rank, share: arch.share,
    colors: arch.colors, decksSeen: arch.decks,
    blurb: `${arch.tier}-tier on onepiece.gg's OP17 Standard list — ${arch.share}% of 758 placed decks from 34 events.`,
    source: arch.url, countsInferred: false, measuredSlots: d.measured,
    list: d.list, skipped: [], notes: d.notes
  });
}

// Edward.Newgate is onepiece.gg's largest UNRATED archetype (15 placed decks, below its
// 20-deck publication threshold), so it has no measured card table at all. PLAN.md D5.
{
  const d = metaDeck({ leader: 'OP02-001', mostPlayed: [] });
  decks.push({
    key: 'op02-001', name: 'Edward.Newgate', kind: 'meta', leader: 'OP02-001',
    tier: '—', rank: 10, share: null, colors: 'Red', decksSeen: 15,
    blurb: "onepiece.gg's largest unrated archetype — 15 placed decks, under its 20-deck threshold to publish a card table.",
    source: 'https://onepiece.gg/meta/op02-001-edwardnewgate-standard-op17/',
    countsInferred: true, measuredSlots: 0, list: d.list, skipped: [],
    notes: ['onepiece.gg publishes no card table for this archetype, so every slot is inferred.']
  });
}

const header = `// data/decks.js — GENERATED by tools/build-decks.mjs. Do not edit by hand.
//
// The deck registry decides the pool: a card not in a registered deck is not in the game.
// Every slot carries its provenance — 'measured' is onepiece.gg's own most-played table for
// that archetype (with its inclusion rate), 'inferred' was chosen to complete a legal 50.
// See PLAN.md D5.
`;
await writeFile(join(ROOT, 'data', 'decks.js'), `${header}
(function (NS) {
  'use strict';
  NS.decks = ${JSON.stringify(decks, null, 2).split('\n').map((l, i) => (i ? '  ' + l : l)).join('\n')};
}(window.OP = window.OP || {}));
`);

console.log('deck            leader      cards  measured  inferred  notes');
for (const d of decks) {
  const total = d.list.reduce((a, x) => a + x[1], 0);
  const meas = d.list.filter((x) => x[2] === 'measured').reduce((a, x) => a + x[1], 0);
  console.log(`${d.key.padEnd(15)} ${d.leader.padEnd(11)} ${String(total).padStart(3)}  ${String(meas).padStart(8)}  ${String(total - meas).padStart(8)}  ${d.notes.length || ''}`);
  d.notes.forEach((n) => console.log(`      note: ${n}`));
  if (d.skipped && d.skipped.length) console.log(`      skipped (does not compile): ${d.skipped.join(', ')}`);
}
