#!/usr/bin/env node
// tools/build-printed.mjs — turn the gitignored scratch/cards/*.html scrapes of
// Bandai's official card list into data/printed.js, the printed-text pack.
//
// This is the ONLY path by which published card text enters the repo, and the
// pack records the set and rules version it was built against at the top
// (CARD-GAME-LESSONS-5.md §7.4: "in a year nobody will know whether a card is
// wrong or just old").
//
// One entry per CARD NUMBER. Parallel arts (…_p1, _p2) carry identical text and
// are folded into the base entry; the alt-art ids are kept in `arts` so the art
// pipeline knows how many illustrations exist for a number.
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const IN = join(ROOT, 'scratch', 'cards');
const OUT = join(ROOT, 'data', 'printed.js');

const ent = (s) => s
  .replace(/<br\s*\/?>/gi, '\n')
  .replace(/<[^>]+>/g, '')
  .replace(/&lt;/g, '<').replace(/&gt;/g, '>')
  .replace(/&quot;/g, '"').replace(/&#0?39;|&apos;/g, "'")
  .replace(/&nbsp;/g, ' ')
  .replace(/&amp;/g, '&')
  .replace(/[ \t]+/g, ' ')
  .replace(/ *\n */g, '\n')
  .trim();

const field = (block, cls) => {
  const m = block.match(new RegExp(`<div class="${cls}">(?:<h3>[^<]*<\\/h3>)?([\\s\\S]*?)<\\/div>`));
  return m ? ent(m[1].replace(/<h3>[\s\S]*?<\/h3>/, '')) : '';
};

const dash = (v) => (v === '-' || v === '' || v === '—' ? null : v);
const num = (v) => { const d = dash(v); return d === null ? null : Number(String(d).replace(/[^\d-]/g, '')); };

const files = (await readdir(IN)).filter((f) => /^series-\d+\.html$/.test(f)).sort();
const cards = new Map();
let blocks = 0, arts = 0;

for (const f of files) {
  const html = await readFile(join(IN, f), 'utf8');
  // Each card is one <dl class="modalCol" id="…"> … </dl>
  const re = /<dl class="modalCol" id="([^"]+)">([\s\S]*?)<\/dl>/g;
  let m;
  while ((m = re.exec(html))) {
    blocks++;
    const domId = m[1];
    const b = m[2];
    const info = [...b.matchAll(/<span>([^<]*)<\/span>/g)].map((x) => ent(x[1]));
    const nameM = b.match(/<div class="cardName">([\s\S]*?)<\/div>/);
    if (!nameM || info.length < 3) continue;
    const id = info[0];
    const rarity = info[1];
    const category = info[2].toUpperCase();
    if (id !== domId) arts++; // a parallel art: dom id carries a _pN suffix

    const attrM = b.match(/<div class="attribute">[\s\S]*?<i>([^<]*)<\/i>/);
    const rec = {
      id,
      name: ent(nameM[1]),
      category,
      rarity,
      cost: num(field(b, 'cost')),
      power: num(field(b, 'power')),
      counter: num(field(b, 'counter')),
      color: (dash(field(b, 'color')) || '').split('/').map((s) => s.trim()).filter(Boolean),
      attribute: attrM ? [ent(attrM[1])] : [],
      types: (dash(field(b, 'feature')) || '').split('/').map((s) => s.trim()).filter(Boolean),
      text: field(b, 'text') || '',
      trigger: field(b, 'trigger') || '',
      block: dash(field(b, 'block')),
      set: field(b, 'getInfo'),
      arts: [domId],
    };
    // Rules 2-9: only Leaders have Life, and only Characters/Events/Stages have
    // cost. The official list reuses one "Cost" slot for both, so split it here
    // by category rather than leaving every consumer to guess. Verified against
    // OP14-020 (Life 5), OP01-002 (Life 4) and OP02-001 (Life 6).
    if (rec.category === 'LEADER') { rec.life = rec.cost; rec.cost = null; }
    else {
      rec.life = null;
      // The official list renders a printed cost of 0 as "-". Verified against
      // the OP04-016 card face, which shows a 0 in the cost circle while the
      // list prints "-". Cost is mandatory on every non-Leader (rules 2-7-5),
      // so "-" here is 0 and never "unknown".
      if (rec.cost === null) rec.cost = 0;
    }
    const prev = cards.get(id);
    if (prev) { if (!prev.arts.includes(domId)) prev.arts.push(domId); continue; }
    cards.set(id, rec);
  }
}

const byId = [...cards.values()].sort((a, b) => a.id.localeCompare(b.id, 'en'));
const counts = byId.reduce((a, c) => ((a[c.category] = (a[c.category] || 0) + 1), a), {});

const header = `// data/printed.js — GENERATED by tools/build-printed.mjs. Do not edit by hand.
//
// Printed card text from Bandai's official ONE PIECE CARD GAME card list
// (https://en.onepiece-cardgame.com/cardlist/), scraped ${new Date().toISOString().slice(0, 10)}.
// Card faces show this text verbatim; see CLAUDE.md for the fidelity regime and
// NOTICE.md for the rights posture.
//
// BUILT AGAINST
//   card list        every series offered on the official list as of ${new Date().toISOString().slice(0, 10)}
//                    (through OP-17, ST-36, EB-03, PRB-02, promos)
//   rules            Comprehensive Rules v1.2.1, last updated 2026-08-28
//   cards            ${byId.length} distinct card numbers, ${blocks} printings
//   by category      ${Object.entries(counts).map(([k, v]) => `${k} ${v}`).join(', ')}
`;

const body = byId.map((c) => '  ' + JSON.stringify(c)).join(',\n');
await writeFile(OUT, `${header}
(function (NS) {
  'use strict';
  NS.printed = [
${body}
  ];
  NS.printedMeta = {
    cardList: 'https://en.onepiece-cardgame.com/cardlist/',
    scraped: '${new Date().toISOString().slice(0, 10)}',
    rules: 'Comprehensive Rules v1.2.1 (2026-08-28)',
    cards: ${byId.length},
    printings: ${blocks}
  };
}(window.OP = window.OP || {}));
`);

console.log(`${byId.length} distinct card numbers from ${blocks} printings (${arts} parallel arts folded)`);
for (const [k, v] of Object.entries(counts)) console.log(`  ${k.padEnd(10)} ${v}`);
